<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/assets/images/favicon.ico">

    <title><?php echo $this->title;?></title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/assets/css/starter-template.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="<?php echo $this->home; ?>">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="<?php echo $this->home; ?>">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->history; ?>">History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Setting</a>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="container">

    <div class="starter-template">
        <h1><?php echo $this->header; ?></h1>
        <?php if (!empty($this->errors) && is_array($this->errors)) { ?>
            <div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i>
                <?php foreach($this->errors as $error){ ?>
                    <p class="text-warning"><?php echo $error; ?></p>
                <?php } ?>
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
        <?php } ?>
        <form class="form-inline" action="/index/request-add">
            <div class="form-group mx-sm-4 mb-2">
                <label for="inputDomain" class="sr-only">Domain:</label>
                <input type="text" name="domain" class="form-control id="inputDomain" placeholder="domain.com">
            </div>
            <div class="form-group mx-sm-4 mb-2">
                <label for="inputKeyword" class="sr-only">Keyword:</label>
                <input type="text" name="keyword" class="form-control" id="inputKeyword" placeholder="keyword">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Get Position</button>
        </form>
    </div>

</main><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="/assets/js/vendor/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>
